# -*- coding: utf-8 -*-
"""kadai_013

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xn6Bwo0CRSJmrTLPV7uc76k_TwZng7FE
"""

def calculate_total(price,consumption_tax):
    total = price * (1 +consumption_tax / 100)
    return(total)

x = calculate_total(1000,10)

print(f"{x}円（税込）")
