# -*- coding: utf-8 -*-
"""kadai_015

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m_i4M2jugfagUgxYhLvdUjZfsdaCJcob
"""

class Human:
      def __init__(self,name,age):
        self.name = name
        self.age = age

      def set_name(self,name):
        self.name = name
      def set_age(self,age):
        self.age = age

      def printinfo(self):
        print("【氏名】",self.name)
        print("【ご年齢】",self.age)

human = Human("HikaruYoshiki",36)

human.printinfo()