# -*- coding: utf-8 -*-
"""kadai_017.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12Js4lKxrY8UbylU08Dq6U6bfGYqD3IuK
"""

class Human:
    def __init__(self, name, age):
     # 属性の定義
        self.name = name
        self.age = age

    def check_adult(self):
        if self.age >= 20 :
          print("{}さんは大人です！".format(self.name))
        else:
          print("{}さんは未成年です・・・".format(self.name))

# インスタンスを作成
data = [["輝",36],["友梨香",35],["光祥",3],["花希",0],["久野",88],["八島",111]]

# human_listへインスタンスのリストを追加
human_list = []
for d in data:
    human_list.append((d[0], d[1]))

# human_listより各インスタンスのメソッドを実行
i = 0
for h in human_list:
  Human(h[0], h[1]).check_adult()