# -*- coding: utf-8 -*-
"""kadai_014

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19I3Pn9uAWMDJ9Tk2trfJL0VZnWuvwqmg
"""

def total(price1,price2):
    tax = 1.1
    total = (price1 + price2) * tax
    return(total)

x = total(100,200)

print (f"{x}円（税込）")

