# -*- coding: utf-8 -*-
"""kadai_008.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fxiTZTjoeixdo5pCPOdWzynYTIATot1Z
"""

import random

num = random.randint()

print(num)

import random

var = random.randint(1,10)

if var % 3 == 0 and var % 5 == 0:
    print("FizzBuzz")

elif var % 3 == 0:
    print("Fizz")

elif var % 5 == 0:
    print("Buzz")

else:
    print(var)