# -*- coding: utf-8 -*-
"""kadai_011

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qLTcJFaV0np6rkD-Q_tMrrO6Faa5X8f_
"""

list = ["水","金","地","火","木","土","天","海","冥"]

for value in list:
    print(value)


index = 0
while index < 9:
  print (list[index])
  index = index + 1