# -*- coding: utf-8 -*-
"""kadai_005.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OiuvXb1gXeBEdHltaJBAtxt1FTVPRr7r
"""

the_top_side = 10
the_bottom_side = 20
the_height = 5
the_surface_areas = (the_top_side + the_bottom_side)*the_height/2

print(str(the_surface_areas)+"㎠")
